# Generated by Django 3.0 on 2021-06-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_migrate_sha1_passwords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(max_length=255, null=True, upload_to='media'),
        ),
    ]
