# Generated by Django 3.0 on 2023-01-05 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_notificaciones_imagenes_notificacion'),
        ('user_auth', '0003_auto_20210615_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Empresas'),
        ),
    ]
