# Generated by Django 4.2 on 2024-04-30 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_user_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_alternativo',
            field=models.EmailField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='expired_password',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='User_sin_email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_user_sin_email',
            },
        ),
    ]
