# Generated by Django 3.0 on 2021-05-26 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('nit', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=255)),
                ('activo', models.BooleanField(blank=True, default=True)),
                ('email', models.CharField(max_length=255)),
                ('direccion_comercial', models.CharField(max_length=255)),
                ('nombre_comercial', models.CharField(max_length=255)),
                ('fel', models.BooleanField(blank=True, default=False)),
                ('usuario', models.CharField(max_length=255)),
                ('apikey', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Localidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=255)),
                ('activo', models.BooleanField(blank=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Empresas')),
            ],
        ),
    ]
