# Generated by Django 3.0 on 2022-06-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_departamento_user_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_departamento',
            name='es_admin',
            field=models.BooleanField(default=False),
        ),
    ]
