# Generated by Django 3.0 on 2022-10-27 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_menu_colores_fondo_menu_colores_opciones_menu_configuracion_usuarios_menu_imagenes_notificaciones_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificaciones_imagenes',
            name='notificacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Notificaciones'),
        ),
    ]
