# Generated by Django 3.0 on 2023-08-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_notificaciones_imagenes_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresas',
            name='no_empresa_conta',
            field=models.SmallIntegerField(default=None, null=True),
        ),
    ]
