# Generated by Django 3.0 on 2021-12-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_negociaciones_dci_negociaciones_dci_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='negociaciones_dci_detalle',
            name='estado',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
