# Generated by Django 3.0 on 2022-01-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_negociaciones_dci_detalle_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuestas_voz_clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NoCliente', models.IntegerField()),
                ('telefono', models.TextField()),
                ('pregunta_evalua_servicio', models.CharField(choices=[('MALO', 'Malo'), ('REGULAR', 'Regular'), ('MUY_BUENO', 'Muy Bueno'), ('EXCELENTE', 'Excelente')], default='MALO', max_length=9)),
                ('pregunta_comunicacion', models.CharField(choices=[('TELEFONICAMENTE', 'Telefónicamente'), ('PERSONALMENTE', 'Personalmente'), ('WHATSAPP', 'WhatsApp'), ('OTRO', 'Otro')], default='TELEFONICAMENTE', max_length=15)),
                ('detalle_pregunta_comunicacion', models.TextField(null=True)),
                ('pregunta_realizar_pedido', models.CharField(choices=[('VENDEDOR_LLAMA', 'Vendedor le llama'), ('USTED_LLAMA', 'Usted llama al vendedor')], default='VENDEDOR_LLAMA', max_length=14)),
                ('pregunta_metodo_pedido', models.CharField(choices=[('TELEFONO', 'Teléfono'), ('VISITA', 'Visita'), ('OTRO', 'Otro')], default='TELEFONO', max_length=8)),
                ('detalle_pregunta_metodo_pedido', models.TextField(null=True)),
                ('pregunta_vendedor_ofrece', models.BooleanField(default=False)),
                ('pregunta_cambio_precio', models.BooleanField(default=False)),
                ('pregunta_visitas_vendedor', models.CharField(choices=[('SEMANAL', 'Semanal'), ('QUINCENAL', 'Quincenal'), ('MENSUAL', 'Mensual'), ('DOS_MESES', 'Dos Meses'), ('NUNCA', 'Nunca')], default='SEMANAL', max_length=9)),
                ('comentario', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
