# Generated by Django 3.0 on 2022-03-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_encuestas_voz_clientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuestas_sala_ventas',
            name='encontro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='encuestas_sala_ventas',
            name='observacion_recomendar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='encuestas_sala_ventas',
            name='ofrecio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='encuestas_sala_ventas',
            name='recomendar',
            field=models.BooleanField(default=False),
        ),
    ]
