# Generated by Django 3.0 on 2022-08-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_planeacion_demanda_planeacion_demanda_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='planeacion_demanda_detalle',
            name='descripcion',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
