# Generated by Django 3.0 on 2022-12-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_planeacion_demanda_detalle_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizaciones',
            name='formaenvio',
            field=models.IntegerField(blank=True, db_column='FormaEnvio', null=True),
        ),
        migrations.AddField(
            model_name='cotizaciones',
            name='nocontenedor',
            field=models.CharField(blank=True, db_column='NoContenedor', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='detalle_cotizaciones',
            name='nolote',
            field=models.IntegerField(blank=True, db_column='NoLote', null=True),
        ),
    ]
