# Generated by Django 3.0 on 2024-02-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_auto_20221230_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente_prospecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=15)),
                ('nombre_cliente', models.CharField(max_length=300)),
                ('nombre_contacto', models.CharField(max_length=300)),
                ('direccion_entrega', models.CharField(max_length=300)),
                ('nombre_negocio', models.CharField(max_length=300)),
                ('direccion_fiscal', models.CharField(max_length=500)),
                ('tipo_negocio', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=320, null=True)),
                ('cumpleanios_contacto', models.DateField(null=True)),
                ('observaciones', models.CharField(max_length=1000, null=True)),
                ('rtu_path', models.CharField(max_length=255, null=True)),
                ('dpi_path', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
