# Generated by Django 3.0 on 2024-02-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0010_cliente_prospecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente_prospecto',
            name='nombre_vendedor',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
