# Generated by Django 3.0 on 2024-02-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0011_cliente_prospecto_nombre_vendedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente_actualizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_cliente', models.CharField(max_length=30)),
                ('razon_social', models.CharField(max_length=300)),
                ('nit', models.CharField(max_length=15, null=True)),
                ('direccion_fiscal', models.CharField(max_length=300, null=True)),
                ('direccion_entrega', models.CharField(max_length=300, null=True)),
                ('otra_sucursal', models.CharField(max_length=300, null=True)),
                ('nombre_vendedor', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
