# Generated by Django 3.0 on 2024-02-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0012_cliente_actualizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente_actualizacion',
            name='razon_social',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
