# Generated by Django 4.2 on 2024-03-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0013_auto_20240228_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizaciones',
            name='nosucursal',
            field=models.IntegerField(blank=True, db_column='NoSucursal', null=True),
        ),
    ]
