# Generated by Django 4.2 on 2024-04-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0014_cotizaciones_nosucursal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente_actualizacion',
            name='dpi_path',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cliente_actualizacion',
            name='rtu_path',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
