# Generated by Django 3.0 on 2024-05-09 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0015_cliente_actualizacion_dpi_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente_sv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_cliente', models.CharField(max_length=20)),
                ('cliente', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=150)),
                ('direccion_fiscal', models.CharField(max_length=300, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto_sv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto', models.CharField(max_length=20)),
                ('producto', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_producto_sv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_producto', models.CharField(max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto_sv_igualdad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_producto', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('producto_sv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Producto_sv')),
            ],
        ),
        migrations.AddField(
            model_name='producto_sv',
            name='tipo_producto_sv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Tipo_producto_sv'),
        ),
        migrations.CreateModel(
            name='Orden_compra_sv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('path_factura', models.CharField(max_length=255)),
                ('path_recibo', models.CharField(max_length=255)),
                ('path_transferencia', models.CharField(max_length=255)),
                ('anulada', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('cliente_sv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Cliente_sv')),
            ],
        ),
        migrations.CreateModel(
            name='Orden_compra_detalle_sv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=14)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('orden_compra_sv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Orden_compra_sv')),
                ('producto_sv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Producto_sv')),
            ],
        ),
    ]
