# Generated by Django 4.2 on 2024-05-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0016_auto_20240509_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden_compra_detalle_sv',
            name='cantidad',
            field=models.DecimalField(decimal_places=4, max_digits=14),
        ),
        migrations.AlterField(
            model_name='orden_compra_detalle_sv',
            name='precio',
            field=models.DecimalField(decimal_places=4, max_digits=14),
        ),
        migrations.AlterField(
            model_name='orden_compra_detalle_sv',
            name='total',
            field=models.DecimalField(decimal_places=4, max_digits=14),
        ),
        migrations.AlterField(
            model_name='orden_compra_sv',
            name='total',
            field=models.DecimalField(decimal_places=4, max_digits=14),
        ),
    ]
