# Generated by Django 4.2 on 2024-05-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0017_alter_orden_compra_detalle_sv_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden_compra_detalle_sv',
            name='cerrado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orden_compra_detalle_sv',
            name='observacion',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='orden_compra_detalle_sv',
            name='path_respaldo',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orden_compra_detalle_sv',
            name='porcentaje_comision',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='orden_compra_detalle_sv',
            name='tipo_cambio',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='orden_compra_detalle_sv',
            name='valor_comision_dolar',
            field=models.DecimalField(decimal_places=4, default=None, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='orden_compra_detalle_sv',
            name='valor_comision_quetzal',
            field=models.DecimalField(decimal_places=4, default=None, max_digits=14, null=True),
        ),
    ]
