# Generated by Django 4.2 on 2024-06-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0018_orden_compra_detalle_sv_cerrado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingreso_devolucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendedor', models.CharField(max_length=100)),
                ('cliente', models.CharField(max_length=300)),
                ('fecha', models.DateTimeField()),
                ('producto', models.CharField(max_length=300)),
                ('factura', models.CharField(max_length=50)),
                ('motivo', models.CharField(choices=[('VENDEDOR', 'Error Vendedor'), ('CLIENTE', 'Error Cliente'), ('PRESENTACION', 'Presentación del Producto'), ('OTRO', 'Otro')], default='PRESENTACION', max_length=12)),
                ('otro_motivo', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
