from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.login),
    path('get_users/', views.get_users),
    path('get_clientes/', views.get_clientes),
    path('get_info_cliente/', views.get_info_cliente),
    path('get_vencidos_cliente/', views.get_vencidos_cliente),
    path('get_saldo_cliente/', views.get_saldo_cliente),
    path('get_venta_cruzada/', views.get_venta_cruzada),
    path('get_productos/', views.get_productos),
    path('get_productos_lost/', views.get_productos_lost),
    path('get_motivos/', views.get_motivos),
    path('grabar_venta_perdida/', views.grabar_venta_perdida),
    path('get_info_producto/', views.get_info_producto),
    path('grabar_envio/', views.grabar_envio),
    path('get_existencias/', views.get_existencias),
    path('get_producto_transito/', views.get_producto_transito),
    path('get_pedido_dia/', views.get_pedido_dia),
    path('get_comisiones/', views.get_comisiones),
    path('get_cobrado_dia/', views.get_cobrado_dia),
    path('get_ventas_al_dia/', views.get_ventas_al_dia),
    path('get_contado_con_saldo/', views.get_contado_con_saldo),
    path('get_registro_visitas/', views.get_registro_visitas),
    path('get_save_cita/', views.get_save_cita),
    path('get_citas_vendedor/', views.get_citas_vendedor),
    path('save_cita/', views.save_cita),
    path('delete_cita/', views.delete_cita),
    path('get_devoluciones/', views.get_devoluciones),
    path('get_semanas/', views.get_semanas),
    path('get_no_empleado_boletas/', views.get_no_empleado_boletas),
    path('get_periodos/', views.get_periodos),
    path('get_boleta/', views.get_boleta),
    path('save_firma/', views.save_firma),
    path('get_orden_pedidos_sin_entregar/', views.get_orden_pedidos_sin_entregar),
    path('get_detalles_pedidos_sin_entregar/', views.get_detalles_pedidos_sin_entregar),
    path('save_geo/', views.save_geo),
    path('save_out/', views.save_out),
    path('get_meses_vendedores/', views.get_meses_vendedores),
    path('get_auditoria_clientes/', views.get_auditoria_clientes),
    path('get_auditoria_info_cliente/', views.get_auditoria_info_cliente),
    path('save_auditoria_verificacion/', views.save_auditoria_verificacion),
    path('get_auditoria_historial/', views.get_auditoria_historial),
    path('get_ventas_historial_citas/', views.get_ventas_historial_citas),
    path('save_clientes_prospecto/', views.save_clientes_prospecto),
    path('get_vales/', views.get_vales),
    path('get_dashboard_presupuesto/', views.get_dashboard_presupuesto),
]
