# Generated by Django 4.2 on 2024-07-29 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mcuadratica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descri', models.CharField(blank=True, db_column='Descri', max_length=100, null=True)),
                ('ctacontable', models.ForeignKey(blank=True, db_column='CtaContable', max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, to='contabilidad.mcuentas')),
            ],
        ),
    ]
