# Generated by Django 4.2 on 2024-08-06 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0008_alter_msocios_ctacontable_alter_msocios_moneda'),
        ('contabilidad', '0001_initial'),
        ('bancos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tpago01',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(blank=True, db_column='Serie', max_length=20, null=True)),
                ('numero', models.IntegerField(blank=True, db_column='Numero', null=True)),
                ('fechapago', models.DateField(blank=True, db_column='FechaPago', null=True)),
                ('fechasys', models.DateField(blank=True, db_column='FechaSys', null=True)),
                ('fechaconta', models.DateField(blank=True, db_column='FechaConta', null=True)),
                ('tipopago', models.CharField(blank=True, db_column='TipoPago', max_length=20, null=True)),
                ('ref1', models.CharField(blank=True, db_column='Ref1', max_length=20, null=True)),
                ('ref2', models.CharField(blank=True, db_column='Ref2', max_length=20, null=True)),
                ('comentario', models.CharField(blank=True, db_column='Comentario', max_length=400, null=True)),
                ('montorecibo', models.DecimalField(blank=True, db_column='MontoRecibo', decimal_places=2, max_digits=18, null=True)),
                ('status', models.BooleanField(blank=True, db_column='Status', null=True)),
                ('partida', models.IntegerField(blank=True, null=True)),
                ('letras', models.CharField(blank=True, db_column='Letras', max_length=200, null=True)),
                ('pagafacturas', models.BooleanField(blank=True, db_column='PagaFacturas', null=True)),
                ('tcusd', models.DecimalField(blank=True, db_column='TcUsd', decimal_places=6, max_digits=18, null=True)),
                ('login', models.CharField(blank=True, db_column='Login', max_length=20, null=True)),
                ('horasys', models.TimeField(blank=True, db_column='HoraSys', null=True)),
                ('nonegociable', models.BooleanField(blank=True, db_column='NoNegociable', null=True)),
                ('ctacontableban', models.ForeignKey(blank=True, db_column='CtaContableBan', null=True, on_delete=django.db.models.deletion.CASCADE, to='contabilidad.mcuentas')),
                ('cueban', models.ForeignKey(blank=True, db_column='Cueban', null=True, on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.mbancos')),
                ('idsocio', models.ForeignKey(blank=True, db_column='IdSocio', null=True, on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.msocios')),
                ('moneda', models.ForeignKey(blank=True, db_column='Moneda', max_length=3, null=True, on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.mmoneda')),
            ],
        ),
        migrations.CreateModel(
            name='Tpago02',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseentry', models.IntegerField(blank=True, db_column='BaseEntry', null=True)),
                ('serie', models.CharField(blank=True, db_column='Serie', max_length=20, null=True)),
                ('numero', models.CharField(blank=True, db_column='Numero', max_length=20, null=True)),
                ('fecha', models.DateField(blank=True, db_column='Fecha', null=True)),
                ('doctotal', models.DecimalField(blank=True, db_column='DocTotal', decimal_places=2, max_digits=18, null=True)),
                ('abonos', models.DecimalField(blank=True, db_column='Abonos', decimal_places=2, max_digits=18, null=True)),
                ('pago', models.DecimalField(blank=True, db_column='Pago', decimal_places=2, max_digits=18, null=True)),
                ('tcusd', models.DecimalField(blank=True, db_column='TcUsd', decimal_places=6, max_digits=18, null=True)),
                ('ctacontable', models.ForeignKey(blank=True, db_column='CtaContable', max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, to='contabilidad.mcuentas')),
                ('tpago01', models.ForeignKey(db_column='Tpago01', on_delete=django.db.models.deletion.CASCADE, to='bancos.tpago01')),
            ],
        ),
    ]
