# Generated by Django 3.0 on 2021-05-26 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('presupuestos', '0002_auto_20210526_1713'),
        ('rrhh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_configuracion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='users_configuracion',
            name='user_jefe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_jefe', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='puestos',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.Departamentos'),
        ),
        migrations.AddField(
            model_name='departamentos',
            name='departamento_presupuesto',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='presupuestos.Departamentos'),
        ),
    ]
