# Generated by Django 3.0 on 2021-06-08 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0003_auto_20210608_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puestos',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rrhh.Departamentos'),
        ),
        migrations.AlterField(
            model_name='users_configuracion',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rrhh.Departamentos'),
        ),
        migrations.AlterField(
            model_name='users_configuracion',
            name='puesto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rrhh.Puestos'),
        ),
    ]
