# Generated by Django 3.0 on 2021-06-08 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0005_empresas_usuario'),
        ('rrhh', '0004_auto_20210608_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamentos',
            name='departamento_presupuesto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='presupuestos.Departamentos'),
        ),
    ]
