# Generated by Django 3.0 on 2021-06-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0005_auto_20210608_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamentos',
            name='codigo',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
