# Generated by Django 3.0 on 2021-11-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0008_vales'),
    ]

    operations = [
        migrations.AddField(
            model_name='vales',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
