# Generated by Django 3.0 on 2021-11-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0009_vales_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='vales',
            name='correlativo',
            field=models.IntegerField(default=0),
        ),
    ]
