# Generated by Django 3.0 on 2021-11-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0010_vales_correlativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados_suspensiones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleado', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('estado', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_regreso', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
