# Generated by Django 3.0 on 2021-11-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0011_empleados_suspensiones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados_suspensiones',
            name='fecha_regreso',
            field=models.DateTimeField(null=True),
        ),
    ]
