# Generated by Django 3.0 on 2022-01-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0013_horas_extras_horas_extras_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='horas_extras',
            name='departamento',
            field=models.IntegerField(null=True),
        ),
    ]
