# Generated by Django 3.0 on 2022-01-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0014_horas_extras_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horas_extras_detalle',
            name='horas_dobles',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='horas_extras_detalle',
            name='horas_simples',
            field=models.FloatField(null=True),
        ),
    ]
