# Generated by Django 3.0 on 2022-04-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0016_planificacion_vacaciones_planificacion_vacaciones_detalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datos_empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleado_id', models.IntegerField()),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('dpi', models.CharField(max_length=25)),
                ('departamento_dpi', models.CharField(max_length=70)),
                ('municipio_dpi', models.CharField(max_length=70)),
                ('direccion', models.CharField(max_length=150)),
                ('estado_civil', models.SmallIntegerField()),
                ('bool_cambio_datos', models.BooleanField(default=False)),
                ('bool_actualizados', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
