# Generated by Django 3.0 on 2022-05-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0017_datos_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos_empleado',
            name='mail',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datos_empleado',
            name='nit',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='datos_empleado',
            name='telefono',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
