# Generated by Django 3.0 on 2022-05-16 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0018_auto_20220504_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagos_programados_empleados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_empleado', models.CharField(max_length=255, null=True)),
                ('dpi', models.CharField(default=True, max_length=255)),
                ('no_credito', models.CharField(max_length=255)),
                ('nombres', models.CharField(max_length=255, null=True)),
                ('apellidos', models.CharField(max_length=255, null=True)),
                ('empresa', models.CharField(max_length=255, null=True)),
                ('deudor', models.CharField(max_length=255, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('capital', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('interes', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('cuota', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
