# Generated by Django 3.0 on 2022-05-23 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0019_pagos_programados_empleados'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comision_Regla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_cliente', models.IntegerField(null=True)),
                ('tipo_producto', models.CharField(choices=[('C', 'Cuadril'), ('M', 'Mixto')], max_length=1, null=True)),
                ('no_producto', models.IntegerField(null=True)),
                ('comision_base', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comision_fuera_rango', models.DecimalField(decimal_places=2, max_digits=2)),
                ('es_porcentaje', models.BooleanField(default=True)),
                ('descuento_precio', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('no_vendedor', models.IntegerField(null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comision_Regla_Rangos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_rango_dias', models.SmallIntegerField()),
                ('fin_rango_dias', models.SmallIntegerField()),
                ('comision', models.DecimalField(decimal_places=2, max_digits=5)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('regla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.Comision_Regla')),
            ],
        ),
    ]
