# Generated by Django 3.0 on 2022-05-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0020_comision_regla_comision_regla_rangos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos_programados_empleados',
            name='movido_nomina',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='pagos_programados_empleados',
            name='saldo_pendiente',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
