# Generated by Django 3.0 on 2022-05-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0021_auto_20220523_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos_programados_empleados',
            name='dpi',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
