# Generated by Django 3.0 on 2022-06-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0022_auto_20220523_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos_programados_empleados',
            name='tipo_movimiento',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
