# Generated by Django 3.0 on 2022-07-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0023_pagos_programados_empleados_tipo_movimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comision_regla',
            name='comision_fuera_rango',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
