# Generated by Django 3.0 on 2022-07-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0024_auto_20220712_0826'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comision_Vendedor_Datos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_vendedor', models.IntegerField()),
                ('codigo_empresa', models.IntegerField(null=True)),
                ('no_area', models.IntegerField(null=True)),
                ('nombre_personalizado', models.CharField(max_length=110, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
