# Generated by Django 3.0 on 2022-08-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0025_comision_vendedor_datos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos_programados_empleados',
            name='nomina',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
