# Generated by Django 3.0 on 2022-11-11 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0023_auto_20220128_1611'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rrhh', '0027_libreria_producto_libreria_producto_movimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libreria_tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('clave', models.CharField(max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='libreria_producto',
            name='codigo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='libreria_producto',
            name='unidad_medida',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='libreria_producto_movimiento',
            name='orden_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.Orden_compra'),
        ),
        migrations.CreateModel(
            name='Libreria_ingreso_bodega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('orden_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.Orden_compra')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='libreria_producto',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rrhh.Libreria_tipo'),
        ),
        migrations.AddField(
            model_name='libreria_producto_movimiento',
            name='ingreso_bodega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rrhh.Libreria_ingreso_bodega'),
        ),
    ]
