# Generated by Django 3.0 on 2022-11-29 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0028_auto_20221111_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='libreria_ingreso_bodega',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rrhh.Libreria_tipo'),
        ),
    ]
