# Generated by Django 3.0 on 2023-01-14 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_notificaciones_imagenes_notificacion'),
        ('rrhh', '0029_libreria_ingreso_bodega_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('subsidio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cuenta_subsidio', models.IntegerField(blank=True, null=True)),
                ('cuenta_descuento', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Telefono_descuento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsidio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('facturado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Empresas')),
                ('telefono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.Telefono')),
            ],
        ),
    ]
