# Generated by Django 3.0 on 2023-06-06 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0030_telefono_telefono_descuento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comision_respaldo_modificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_comision_datos', models.IntegerField()),
                ('archivo_respaldo', models.FileField(max_length=500, upload_to='respaldo_comisiones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='comision_regla',
            name='archivo_respaldo',
            field=models.FileField(default=None, max_length=500, null=True, upload_to='respaldo_reglas_comisiones'),
        ),
        migrations.CreateModel(
            name='Comision_regla_respaldo_modificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_respaldo', models.FileField(max_length=500, upload_to='respaldo_reglas_comisiones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comision_regla', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rrhh.Comision_Regla')),
            ],
        ),
    ]
