# Generated by Django 3.0 on 2023-07-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0031_auto_20230606_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='telefono',
            name='activo',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
