# Generated by Django 3.0 on 2023-09-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0032_telefono_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='comision_regla',
            name='fecha_fin',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='comision_regla',
            name='fecha_inicio',
            field=models.DateField(default=None, null=True),
        ),
    ]
