# Generated by Django 3.0 on 2024-04-11 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def forwards_func(apps, schema_editor):
    Estatus = apps.get_model("rrhh", "Estatus")
    db_alias = schema_editor.connection.alias
    Estatus.objects.using(db_alias).bulk_create(
        [
            Estatus(orden="1", estatus="Ingresado", color="#FFFF00", activo=True),
            Estatus(orden="2", estatus="Enviado a autorizar", color="#FF8000", activo=True),
            Estatus(orden="3", estatus="Rechazado", color="#FF0000", activo=True),
            Estatus(orden="4", estatus="Autorizado por Encargado", color="#0000FF", activo=True),
            Estatus(orden="5", estatus="Firma Pendiente", color="#572364", activo=True),
            Estatus(orden="6", estatus="Finalizado", color="#02C028", activo=True),
        ]
    )


def reverse_func(apps, schema_editor):
    Estatus = apps.get_model("rrhh", "Estatus")
    db_alias = schema_editor.connection.alias
    Estatus.objects.using(db_alias).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rrhh', '0033_auto_20230905_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dias_habiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('es_inhabil', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado_jerarquia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_empleado', models.IntegerField()),
                ('id_superior', models.IntegerField(null=True)),
                ('notificar', models.BooleanField(default=False)),
                ('autorizador_auxiliar', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado_solicitud_vacaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_empleado', models.IntegerField()),
                ('trasladada_info_nomina', models.BooleanField(default=False)),
                ('hoja_impresa', models.BooleanField(default=False)),
                ('dias_solicitados', models.SmallIntegerField()),
                ('observacion', models.TextField(blank=True, max_length=500, null=True)),
                ('motivo_rechazo', models.TextField(blank=True, max_length=500, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('eliminado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Estatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('estatus', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado_solicitud_vacaciones_detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.TextField(max_length=20)),
                ('fecha', models.DateField()),
                ('id_database', models.IntegerField(null=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empleado_solicitud_vacaciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.Empleado_solicitud_vacaciones')),
            ],
        ),
        migrations.AddField(
            model_name='empleado_solicitud_vacaciones',
            name='id_jefe_autorizo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, related_name='jefe'),
        ),
        migrations.AddField(
            model_name='empleado_solicitud_vacaciones',
            name='estatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.Estatus'),
        ),
        migrations.AddField(
            model_name='empleado_solicitud_vacaciones',
            name='usuario_imprimio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
