# Generated by Django 4.2 on 2024-05-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0035_dias_semana_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado_solicitud_vacaciones',
            name='medio_dia',
            field=models.BooleanField(default=False),
        ),
    ]
