# Generated by Django 4.2 on 2024-05-17 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_token_two_factor_authentication'),
        ('rrhh', '0036_empleado_solicitud_vacaciones_medio_dia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permisos_estatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('estatus', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Permisos_tipos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dias_permitidos', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Permisos_empleados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_empleado', models.IntegerField()),
                ('observacion', models.TextField(blank=True, max_length=500, null=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('fecha_solicitud', models.DateField()),
                ('trasladada_info_nomina', models.BooleanField(default=False)),
                ('hoja_impresa', models.BooleanField(default=False)),
                ('eliminado', models.BooleanField(default=False)),
                ('motivo_rechazo', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.departamento')),
                ('estatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.permisos_estatus')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.permisos_tipos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usuario_imprimio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_imprimio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
