# Generated by Django 4.2 on 2024-06-13 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rrhh', '0038_log_reprocesar_comisiones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipos_bonos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bonificaciones_empleados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('tipo_periodo', models.CharField(max_length=20)),
                ('no_periodo', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('nomina', models.CharField(max_length=20)),
                ('no_empresa', models.IntegerField()),
                ('empresa', models.CharField(max_length=50)),
                ('no_depto', models.IntegerField()),
                ('departamento', models.CharField(max_length=50)),
                ('no_empleado', models.IntegerField()),
                ('empleado', models.CharField(max_length=50)),
                ('fecha_alta', models.DateField()),
                ('julio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('agosto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('septiembre', models.DecimalField(decimal_places=2, max_digits=8)),
                ('octubre', models.DecimalField(decimal_places=2, max_digits=8)),
                ('noviembre', models.DecimalField(decimal_places=2, max_digits=8)),
                ('diciembre', models.DecimalField(decimal_places=2, max_digits=8)),
                ('enero', models.DecimalField(decimal_places=2, max_digits=8)),
                ('febrero', models.DecimalField(decimal_places=2, max_digits=8)),
                ('marzo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('abril', models.DecimalField(decimal_places=2, max_digits=8)),
                ('mayo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('junio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('promedio_mes', models.DecimalField(decimal_places=2, max_digits=8)),
                ('dias', models.IntegerField()),
                ('bono', models.DecimalField(decimal_places=2, max_digits=8)),
                ('bono_ley', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_1', models.DecimalField(decimal_places=2, max_digits=8)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=8)),
                ('isr', models.DecimalField(decimal_places=2, max_digits=8)),
                ('reten_iva', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_2', models.DecimalField(decimal_places=2, max_digits=8)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.tipos_bonos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
