# Generated by Django 4.2 on 2024-07-18 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mccos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idccos', models.CharField(db_column='IdCcos', max_length=50, unique=True)),
                ('ccosnombre', models.CharField(db_column='CcosNombre', max_length=100)),
                ('codccos', models.CharField(blank=True, db_column='CodCcos', max_length=10, null=True)),
                ('dim', models.DecimalField(db_column='Dim', decimal_places=0, max_digits=1)),
                ('activo', models.BooleanField(db_column='Activo', default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mcuentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctacontable', models.CharField(db_column='CtaContable', max_length=10, unique=True)),
                ('ctanombre', models.CharField(blank=True, db_column='CtaNombre', max_length=100, null=True)),
                ('ctanombre2', models.CharField(blank=True, db_column='CtaNombre2', max_length=100, null=True)),
                ('efecto', models.CharField(blank=True, db_column='Efecto', max_length=1, null=True)),
                ('nivel', models.CharField(blank=True, db_column='Nivel', max_length=1, null=True)),
                ('referencia', models.CharField(blank=True, db_column='Referencia', max_length=10, null=True)),
                ('moneda', models.CharField(blank=True, db_column='Moneda', max_length=3, null=True)),
                ('activo', models.BooleanField(db_column='Activo', default=True)),
                ('ctapadre', models.ForeignKey(blank=True, db_column='CtaPadre', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.mcuentas')),
            ],
        ),
        migrations.CreateModel(
            name='Mpresu01',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, db_column='Fecha', null=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mpresu02',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ene', models.DecimalField(blank=True, db_column='Ene', decimal_places=2, max_digits=18, null=True)),
                ('feb', models.DecimalField(blank=True, db_column='Feb', decimal_places=2, max_digits=18, null=True)),
                ('mar', models.DecimalField(blank=True, db_column='Mar', decimal_places=2, max_digits=18, null=True)),
                ('abr', models.DecimalField(blank=True, db_column='Abr', decimal_places=2, max_digits=18, null=True)),
                ('may', models.DecimalField(blank=True, db_column='May', decimal_places=2, max_digits=18, null=True)),
                ('jun', models.DecimalField(blank=True, db_column='Jun', decimal_places=2, max_digits=18, null=True)),
                ('jul', models.DecimalField(blank=True, db_column='Jul', decimal_places=2, max_digits=18, null=True)),
                ('ago', models.DecimalField(blank=True, db_column='Ago', decimal_places=2, max_digits=18, null=True)),
                ('sep', models.DecimalField(blank=True, db_column='Sep', decimal_places=2, max_digits=18, null=True)),
                ('oct', models.DecimalField(blank=True, db_column='Oct', decimal_places=2, max_digits=18, null=True)),
                ('nov', models.DecimalField(blank=True, db_column='Nov', decimal_places=2, max_digits=18, null=True)),
                ('dic', models.DecimalField(blank=True, db_column='Dic', decimal_places=2, max_digits=18, null=True)),
                ('ctacontable', models.ForeignKey(db_column='CtaContable', on_delete=django.db.models.deletion.CASCADE, to='contabilidad.mcuentas')),
                ('presu01', models.ForeignKey(db_column='idPre', on_delete=django.db.models.deletion.CASCADE, to='contabilidad.mpresu01')),
            ],
        ),
        migrations.CreateModel(
            name='Mgrupoitm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigogrupo', models.CharField(blank=True, db_column='CodigoGrupo', max_length=10, null=True, unique=True)),
                ('grupo', models.CharField(blank=True, db_column='Grupo', max_length=50, null=True)),
                ('almacen', models.SmallIntegerField(blank=True, db_column='Almacen', null=True)),
                ('activo', models.BooleanField(db_column='Activo', default=True)),
                ('ctacostofab', models.ForeignKey(blank=True, db_column='CtaCostoFab', max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ctacostofab', to='contabilidad.mcuentas')),
                ('ctacostovta', models.ForeignKey(blank=True, db_column='CtaCostoVta', max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ctacostovta', to='contabilidad.mcuentas')),
                ('ctadevinv', models.ForeignKey(blank=True, db_column='CtaDevInv', max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ctadevinv', to='contabilidad.mcuentas')),
                ('ctadevventa', models.ForeignKey(blank=True, db_column='CtaDevVenta', max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ctadevventa', to='contabilidad.mcuentas')),
                ('ctaennofac', models.ForeignKey(blank=True, db_column='CtaEnnofac', max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ctaennofac', to='contabilidad.mcuentas')),
                ('ctaingresos', models.ForeignKey(blank=True, db_column='CtaIngresos', max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ctaingresos', to='contabilidad.mcuentas')),
                ('ctainventario', models.ForeignKey(blank=True, db_column='CtaInventario', max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ctainventario', to='contabilidad.mcuentas')),
                ('ctainventario2', models.ForeignKey(blank=True, db_column='CtaInventario2', max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ctainventario2', to='contabilidad.mcuentas')),
                ('ctainventariorp', models.ForeignKey(blank=True, db_column='CtaInventarioRp', max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ctaingresorp', to='contabilidad.mcuentas')),
                ('ctainvtran', models.ForeignKey(blank=True, db_column='CtaInvTran', max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ctainvtran', to='contabilidad.mcuentas')),
            ],
        ),
        migrations.AddField(
            model_name='mcuentas',
            name='grupo',
            field=models.ForeignKey(blank=True, db_column='Grupo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.mgrupoitm'),
        ),
        migrations.AddField(
            model_name='mcuentas',
            name='mccos',
            field=models.ForeignKey(blank=True, max_length=10, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.mccos'),
        ),
    ]
