# Generated by Django 4.2 on 2024-06-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mempresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreempresa', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('nitempresa', models.CharField(blank=True, max_length=20, null=True)),
                ('cloud', models.IntegerField(blank=True, null=True)),
                ('logo', models.CharField(blank=True, max_length=200, null=True)),
                ('ctaclientes', models.CharField(blank=True, max_length=10, null=True)),
                ('tasausd', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('ivatasa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ctaret', models.CharField(blank=True, max_length=10, null=True)),
                ('ctacxp', models.CharField(blank=True, max_length=10, null=True)),
                ('ctaxliq', models.CharField(blank=True, max_length=10, null=True)),
                ('ctaivaxpag', models.CharField(blank=True, max_length=10, null=True)),
                ('ctaexec', models.CharField(blank=True, max_length=10, null=True)),
                ('ctautilidades', models.CharField(blank=True, max_length=10, null=True)),
                ('ctaperdidas', models.CharField(blank=True, max_length=10, null=True)),
                ('usarlector', models.SmallIntegerField(blank=True, null=True)),
                ('rolempresa', models.SmallIntegerField(blank=True, null=True)),
                ('manejainv', models.SmallIntegerField(blank=True, null=True)),
                ('usaconta', models.CharField(blank=True, max_length=2, null=True)),
                ('moneda', models.CharField(blank=True, max_length=3, null=True)),
                ('tipodocto', models.CharField(blank=True, max_length=10, null=True)),
                ('regimen', models.CharField(blank=True, max_length=3, null=True)),
                ('correoemisor', models.CharField(blank=True, max_length=200, null=True)),
                ('postal', models.CharField(blank=True, max_length=10, null=True)),
                ('pais', models.CharField(blank=True, max_length=5, null=True)),
                ('municipio', models.CharField(blank=True, max_length=30, null=True)),
                ('departamento', models.CharField(blank=True, max_length=30, null=True)),
                ('preciomanual', models.SmallIntegerField(blank=True, null=True)),
                ('agretiva', models.CharField(blank=True, max_length=2, null=True)),
                ('razonsocial', models.CharField(blank=True, max_length=100, null=True)),
                ('dirsocial', models.CharField(blank=True, max_length=100, null=True)),
                ('ctaidpimp', models.CharField(blank=True, max_length=10, null=True)),
                ('usafel', models.CharField(blank=True, max_length=2, null=True)),
                ('ctaretiva', models.CharField(blank=True, max_length=10, null=True)),
                ('replegal', models.CharField(blank=True, max_length=200, null=True)),
                ('contadorgeneral', models.CharField(blank=True, max_length=200, null=True)),
                ('certificacion', models.CharField(blank=True, max_length=400, null=True)),
                ('lineasfac', models.SmallIntegerField(blank=True, null=True)),
                ('metodoimporta', models.SmallIntegerField(blank=True, null=True)),
                ('ctaivapgtr', models.CharField(blank=True, max_length=10, null=True)),
                ('ctaivagasto', models.CharField(blank=True, max_length=10, null=True)),
                ('codexport', models.CharField(blank=True, max_length=15, null=True)),
                ('idbodega', models.SmallIntegerField(blank=True, null=True)),
                ('idbodega2', models.SmallIntegerField(blank=True, null=True)),
                ('descripcion', models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True)),
                ('noestable', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('ctaefectivo', models.CharField(blank=True, max_length=10, null=True)),
                ('ctatransfer', models.CharField(blank=True, max_length=10, null=True)),
                ('ctaebanco1', models.CharField(blank=True, max_length=10, null=True)),
                ('ctaebanco2', models.CharField(blank=True, max_length=10, null=True)),
                ('certifica', models.CharField(blank=True, max_length=2, null=True)),
                ('ctaperygan', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
