# Generated by Django 4.2 on 2024-07-22 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mbodega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbodega', models.CharField(blank=True, db_column='NBodega', max_length=100, null=True)),
                ('ubicacion', models.CharField(blank=True, db_column='Ubicacion', max_length=100, null=True)),
                ('activo', models.BooleanField(db_column='Activo', default=True)),
                ('predet', models.BooleanField(db_column='Predet', default=False)),
                ('cencos', models.ForeignKey(blank=True, db_column='CenCos', null=True, on_delete=django.db.models.deletion.CASCADE, to='contabilidad.mccos')),
                ('ctacontable', models.ForeignKey(blank=True, db_column='CtaContable', null=True, on_delete=django.db.models.deletion.CASCADE, to='contabilidad.mcuentas')),
            ],
        ),
        migrations.CreateModel(
            name='Mdocumentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipodocumento', models.CharField(blank=True, db_column='TipoDocumento', max_length=50, null=True)),
                ('fechainicio', models.DateField(blank=True, db_column='FechaInicio', null=True)),
                ('fechavence', models.DateField(blank=True, db_column='FechaVence', null=True)),
                ('serie', models.CharField(blank=True, db_column='Serie', max_length=20, null=True)),
                ('desde', models.IntegerField(blank=True, db_column='Desde', null=True)),
                ('hasta', models.IntegerField(blank=True, db_column='Hasta', null=True)),
                ('ultimano', models.IntegerField(blank=True, db_column='UltimaNo', null=True)),
                ('resolucion', models.CharField(blank=True, db_column='Resolucion', max_length=50, null=True)),
                ('describedocumento', models.CharField(blank=True, db_column='DescribeDocumento', max_length=50, null=True)),
                ('noestable', models.DecimalField(blank=True, db_column='NoEstable', decimal_places=0, max_digits=3, null=True)),
                ('cortecaja', models.CharField(blank=True, db_column='CorteCaja', max_length=2, null=True)),
                ('idsucursal', models.ForeignKey(blank=True, db_column='IdSucursal', max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.mbodega')),
            ],
        ),
        migrations.AddField(
            model_name='mempresa',
            name='ctaiva',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CtaIva'),
        ),
        migrations.CreateModel(
            name='Musers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todas', models.DecimalField(blank=True, db_column='Todas', decimal_places=0, max_digits=1, null=True)),
                ('anulafacturas', models.CharField(blank=True, db_column='AnulaFacturas', max_length=2, null=True)),
                ('cambiaprecios', models.CharField(blank=True, db_column='CambiaPrecios', max_length=2, null=True)),
                ('idbodega1', models.ForeignKey(blank=True, db_column='IdBodega1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idbodega1', to='mantenimiento.mbodega')),
                ('idbodega2', models.ForeignKey(blank=True, db_column='IdBodega2', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idbodega2', to='mantenimiento.mbodega')),
                ('idbodega3', models.ForeignKey(blank=True, db_column='IdBodega3', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idbodega3', to='mantenimiento.mbodega')),
                ('iduser', models.OneToOneField(db_column='IdUser', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('seriefactura', models.ForeignKey(blank=True, db_column='SerieFactura', max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seriefactura', to='mantenimiento.mdocumentos')),
                ('seriepedido', models.ForeignKey(blank=True, db_column='SeriePedido', max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seriepedido', to='mantenimiento.mdocumentos')),
            ],
        ),
        migrations.CreateModel(
            name='Mbancos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cueban', models.CharField(db_column='Cueban', max_length=50)),
                ('nomban', models.CharField(blank=True, db_column='Nomban', max_length=100, null=True)),
                ('chequesigue', models.IntegerField(blank=True, db_column='ChequeSigue', null=True)),
                ('piecheq', models.CharField(blank=True, db_column='Piecheq', max_length=20, null=True)),
                ('sobregiro', models.BooleanField(blank=True, db_column='Sobregiro', null=True)),
                ('moneda', models.CharField(blank=True, db_column='Moneda', max_length=10, null=True)),
                ('bloqueado', models.BooleanField(blank=True, db_column='Bloqueado', null=True)),
                ('saldoinicial', models.DecimalField(blank=True, db_column='SaldoInicial', decimal_places=2, max_digits=18, null=True)),
                ('fechainicial', models.DateField(blank=True, db_column='FechaInicial', null=True)),
                ('ctacon', models.ForeignKey(blank=True, db_column='CtaCon', max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, to='contabilidad.mcuentas')),
            ],
        ),
    ]
