# Generated by Django 4.2 on 2024-07-22 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mantenimiento', '0002_mbodega_mdocumentos_mempresa_ctaiva_musers_mbancos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musers',
            name='idbodega1',
        ),
        migrations.RemoveField(
            model_name='musers',
            name='idbodega2',
        ),
        migrations.RemoveField(
            model_name='musers',
            name='idbodega3',
        ),
        migrations.AlterField(
            model_name='musers',
            name='anulafacturas',
            field=models.BooleanField(db_column='AnulaFacturas', default=False),
        ),
        migrations.AlterField(
            model_name='musers',
            name='cambiaprecios',
            field=models.BooleanField(db_column='CambiaPrecios', default=False),
        ),
        migrations.CreateModel(
            name='Mbodega02',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idbodega', models.ForeignKey(db_column='IdBodega', on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.mbodega')),
                ('iduser', models.ForeignKey(db_column='IdUser', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
