# Generated by Django 4.2 on 2024-07-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0002_mbodega_mdocumentos_mempresa_ctaiva_musers_mbodega02_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mcanales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(db_column='Canal', max_length=50, unique=True)),
                ('ocrcode', models.CharField(blank=True, db_column='OcrCode', max_length=10, null=True)),
                ('agrupador', models.CharField(blank=True, db_column='Agrupador', max_length=30, null=True)),
            ],
        ),
    ]
