# Generated by Django 4.2 on 2024-07-27 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
        ('mantenimiento', '0003_mcanales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mgruposocio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gruposocio', models.CharField(blank=True, db_column='GrupoSocio', max_length=50, null=True)),
                ('ctacontable', models.ForeignKey(blank=True, db_column='CtaContable', null=True, on_delete=django.db.models.deletion.CASCADE, to='contabilidad.mcuentas')),
            ],
        ),
    ]
