# Generated by Django 4.2 on 2024-07-27 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
        ('mantenimiento', '0004_mgruposocio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mgtoi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombregasto', models.CharField(blank=True, db_column='NombreGasto', max_length=100, null=True)),
                ('ctagasto', models.ForeignKey(blank=True, db_column='CtaGasto', max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, to='contabilidad.mcuentas')),
            ],
        ),
    ]
