# Generated by Django 4.2 on 2024-07-27 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
        ('mantenimiento', '0005_mgtoi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mimpuestos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreret', models.CharField(blank=True, db_column='NombreRet', max_length=100, null=True)),
                ('categoria', models.CharField(blank=True, db_column='Categoria', max_length=10, null=True)),
                ('fechavalido', models.DateField(blank=True, db_column='FechaValido', null=True)),
                ('tarifa', models.SmallIntegerField(blank=True, db_column='Tarifa', null=True)),
                ('base', models.CharField(blank=True, db_column='Base', max_length=10, null=True)),
                ('prcimpbase', models.DecimalField(blank=True, db_column='Prcimpbase', decimal_places=2, max_digits=18, null=True)),
                ('ctaconatble', models.ForeignKey(blank=True, db_column='CtaConatble', max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, to='contabilidad.mcuentas')),
            ],
        ),
    ]
