# Generated by Django 4.2 on 2024-08-06 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
        ('mantenimiento', '0007_marticulos_mcategoria_mciudades_mlinea_mlistapre01_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msocios',
            name='ctacontable',
            field=models.ForeignKey(blank=True, db_column='CtaContable', null=True, on_delete=django.db.models.deletion.CASCADE, to='contabilidad.mcuentas'),
        ),
        migrations.AlterField(
            model_name='msocios',
            name='moneda',
            field=models.ForeignKey(blank=True, db_column='Moneda', null=True, on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.mmoneda'),
        ),
    ]
