# Generated by Django 3.0 on 2022-05-11 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('activo', models.BooleanField()),
                ('icono', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evento_inscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleado_id', models.IntegerField()),
                ('puntos_totales', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiniela.Evento')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_partido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('orden', models.SmallIntegerField()),
                ('activo', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiniela.Evento')),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('goles_equipo_1', models.SmallIntegerField(null=True)),
                ('goles_equipo_2', models.SmallIntegerField(null=True)),
                ('penales_equipo_1', models.SmallIntegerField(null=True)),
                ('penales_equipo_2', models.SmallIntegerField(null=True)),
                ('activo', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipo_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo_1_id', to='quiniela.Equipo')),
                ('equipo_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo_2_id', to='quiniela.Equipo')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiniela.Evento')),
                ('tipo_partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiniela.Tipo_partido')),
            ],
        ),
        migrations.CreateModel(
            name='Evento_inscripcion_partido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goles_equipo_1', models.SmallIntegerField(null=True)),
                ('goles_equipo_2', models.SmallIntegerField(null=True)),
                ('penales_equipo_1', models.SmallIntegerField(null=True)),
                ('penales_equipo_2', models.SmallIntegerField(null=True)),
                ('puntos', models.SmallIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evento_inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiniela.Evento_inscripcion')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiniela.Partido')),
            ],
        ),
    ]
