# Generated by Django 3.0 on 2022-08-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiniela', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='hay_penales',
            field=models.BooleanField(default=False),
        ),
    ]
