# Generated by Django 3.0 on 2022-08-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiniela', '0002_partido_hay_penales'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='resultado_congelado',
            field=models.BooleanField(default=False),
        ),
    ]
