# Generated by Django 3.0 on 2022-08-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiniela', '0003_partido_resultado_congelado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago_inscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleado_id', models.IntegerField()),
                ('pago_realizado', models.BooleanField()),
                ('activo', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
