# Generated by Django 3.0 on 2022-06-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_log',
            name='valor_anterior',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='ticket_log',
            name='valor_nuevo',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
