# Generated by Django 3.0 on 2022-07-07 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20220707_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantilla',
            name='agrupacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.Agrupacion'),
        ),
    ]
