# Generated by Django 3.0 on 2022-07-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_plantilla_agrupacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace_usuarios',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
