# Generated by Django 3.0 on 2022-07-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_workspace_usuarios_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='causa',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='titulo',
            field=models.CharField(max_length=70),
        ),
    ]
