# Generated by Django 3.0 on 2022-07-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_auto_20220726_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='aviso_por_vencer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='fecha_aviso_vencido',
            field=models.DateField(blank=True, null=True),
        ),
    ]
