# Generated by Django 3.0 on 2022-08-31 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_auto_20220728_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantilla',
            name='correo_notificacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
