# Generated by Django 3.0 on 2023-02-14 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0008_plantilla_correo_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_iniciativas',
            name='area_proceso',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticket_iniciativas',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.Estado'),
        ),
        migrations.AddField(
            model_name='ticket_iniciativas',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.Agrupacion'),
        ),
        migrations.AddField(
            model_name='ticket_iniciativas',
            name='origen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticket_iniciativas',
            name='prioridad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.Prioridad'),
        ),
        migrations.AddField(
            model_name='ticket_iniciativas',
            name='solucion',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='ticket_iniciativas',
            name='user_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket_iniciativas',
            name='user_creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket_ponderacion',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.Agrupacion'),
        ),
        migrations.AlterField(
            model_name='ticket_iniciativas',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.Ticket'),
        ),
        migrations.AlterField(
            model_name='ticket_ponderacion',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.Ticket'),
        ),
    ]
