# Generated by Django 3.0 on 2022-05-02 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cola_facturacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabla', models.CharField(max_length=255)),
                ('campo', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=255)),
                ('firmado', models.BooleanField(default=False)),
                ('numero_autorizacion', models.CharField(max_length=255, null=True)),
                ('serie', models.CharField(max_length=255, null=True)),
                ('numero', models.CharField(max_length=255, null=True)),
                ('fecha_autorizacion', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='cola_facturacion_detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paso', models.SmallIntegerField()),
                ('data_enviada', models.TextField()),
                ('data_recibida', models.TextField()),
                ('fecha_envio', models.DateTimeField()),
                ('fecha_recibido', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factura_electronica.cola_facturacion')),
            ],
        ),
    ]
