# Generated by Django 3.0 on 2023-03-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura_electronica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cola_facturacion',
            name='anulado',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='cola_facturacion',
            name='fecha_anulado',
            field=models.DateTimeField(null=True),
        ),
    ]
