# Generated by Django 3.0 on 2023-12-22 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factura_electronica', '0002_auto_20230306_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cola_facturacion',
            old_name='key',
            new_name='valor_campo',
        ),
    ]
